Controllers/medicoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using citas.Models;
using Microsoft.EntityFrameworkCore;

namespace citas.Controllers
{
    public class medicoController : Controller
    {
        private readonly CitasContext _context;

        public medicoController(CitasContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public JsonResult getListaMedicos()
        {
            var medicos = _context.Medicos.AsNoTracking().Include(x=>x.Horarios).ToList();

            return Json(medicos);
        }
        
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Title"] | Clínica Chávarri</title>
    <link rel="stylesheet" href="~/css/bulma/bulma.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <script src="~/js/vue/vue.min.js"></script>
    @RenderSection("Styles", required: false)
  </head>
  <body>
    <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
          <a class="navbar-item" asp-area="" asp-controller="Home" asp-action="Index">
            <img src="~/images/logo.jpg" height="28">Clínica Chávarri
          </a>
          <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>
@*       <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-end">
          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              Config
            </a>
          <div class="navbar-dropdown is-right">
            <a class="navbar-item" asp-area="" asp-controller="medico" asp-action="index">
              Médicos
            </a>
          </div>
          </div>
        </div>
      </div> *@
    </nav>
    <hr>
    <div class="container is-fluid">
        @RenderBody()
    </div>
    <footer class="footer">
      <div class="content has-text-centered">
          <p>
            <strong>@DateTime.Now.Year | Clínica Chávarri</strong>
          </p>
      </div>
    </footer>
    <script src="~/js/main.js"></script>
    @RenderSection("Scripts", required: false)
  </body>
</html>